### ISSUE TITLE
Elements inside the dragged item not aligned properly

### ISSUE THREAD

**Issue by huayunh** [pxblue/sortable-list#32]
#### Describe the bug
When dragging, the element being dragged (with `.cdk-drag-preview` class) is not aligned properly.

#### What is the expected behavior?
The dragged element should have the same style, same alignment as all the other list items.

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/8997218/69153507-5f6f3e00-0aac-11ea-8371-4f372d31361e.png)

#### What is your environment?

 Framework
- [x] Angular
- [ ] React
- [x] Ionic
- [ ] React Native

 Browser
- [ ] Internet Explorer
- [ ] Edge
- [ ] Safari
- [x] Chrome
- [ ] Firefox

 Operating System
- [x] MacOS
- [ ] Windows
- [ ] Other

**Comment by huayunh** [comment]
![image](https://user-images.githubusercontent.com/8997218/69199742-ecdf7c00-0b06-11ea-95a7-962cb90eb84b.png)
from PR #34

**Comment by joebochill** [comment]
Is this a bug in the angular branch, or is it only introduced because of your pending change?

**Comment by huayunh** [comment]
The angular one was there before I do anything. 

The ionic one was using a different approach prior to my PR (dragging would change `.cdk-drag-placeholder` instead of `.cdk-drag-preview`), and`.cdk-drag-placeholder` would not cause the misalignment. I changed to use `.cdk-drag-preview` to match the styling of other frameworks.

**Comment by joebochill** [comment]
Can we fix this as part of #33 please?

**Comment by huayunh** [comment]
BTW, this seems to be a problem since Sept 2018. There seems to be no workaround other than the hard fixes I did: https://github.com/angular/components/issues/13288
